# Generated by Django 3.0.7 on 2020-09-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200922_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Sekil Elave Et'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='nomre',
            field=models.IntegerField(verbose_name='Telfon Nomresi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='qiymet',
            field=models.IntegerField(verbose_name='Qiymet'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('e', 'Elektronika'), ('evb', 'Ev Ve Bag'), ('g', 'Geyim')], default='', max_length=3),
        ),
    ]
