# Generated by Django 3.0.7 on 2020-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Sekil Elave Et'),
        ),
    ]
