# Generated by Django 3.0.7 on 2020-09-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200928_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='category',
            field=models.CharField(choices=[('e', 'Elektronika'), ('evb', 'Ev Ve Bag'), ('g', 'Geyim')], max_length=50, verbose_name='Category'),
        ),
    ]
