# Generated by Django 3.0.7 on 2020-10-08 20:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200929_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Mehsul Hakkinda'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('e', 'Elektronika'), ('evb', 'Ev Ve Bag'), ('se', 'Sexsi Esyalar'), ('n', 'Neqliyat'), ('da', 'Dasinmaz Emlak'), ('hvn', 'Heyvanlar'), ('tlf', 'Telefonlar')], default=None, max_length=3, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='category',
            field=models.CharField(choices=[('e', 'Elektronika'), ('evb', 'Ev Ve Bag'), ('se', 'Sexsi Esyalar'), ('n', 'Neqliyat'), ('da', 'Dasinmaz Emlak'), ('hvn', 'Heyvanlar'), ('tlf', 'Telefonlar')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
