# Generated by Django 3.0.7 on 2020-10-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20201011_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packetsarticle',
            name='user',
        ),
        migrations.AddField(
            model_name='packetsarticle',
            name='elan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Article', verbose_name='Elan'),
            preserve_default=False,
        ),
    ]
