# Generated by Django 3.0.7 on 2020-10-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20201011_0122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacketsArticle',
        ),
    ]
