# Generated by Django 3.0.7 on 2020-10-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_packetsarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacketsArticle',
        ),
    ]
