# Generated by Django 3.0.7 on 2020-10-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_delete_packetsarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacketsUsers',
        ),
    ]
