# Generated by Django 3.0.7 on 2020-10-11 11:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_packetsarticle_packetsusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Isdifadeci')),
                ('title', models.CharField(max_length=50, verbose_name='Basliq')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Mehsul Hakkinda')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaradilma Tarixi')),
                ('status', models.CharField(choices=[('e', 'Elektronika'), ('evb', 'Ev Ve Bag'), ('se', 'Sexsi Esyalar'), ('n', 'Neqliyat'), ('da', 'Dasinmaz Emlak'), ('hvn', 'Heyvanlar'), ('tlf', 'Telefonlar')], default=None, max_length=3, verbose_name='category')),
                ('nomre', models.IntegerField(verbose_name='Telfon Nomresi')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Sekil Elave Et')),
                ('qiymet', models.IntegerField(verbose_name='Qiymet')),
            ],
        ),
    ]
