# Generated by Django 3.0.7 on 2020-10-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20201013_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketElan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet', models.CharField(choices=[('nrml', 'Normal'), ('vip', 'VIP'), ('dmnd', 'DIAMOND'), ('pre', 'PREMIUM')], default='Normal', max_length=50, verbose_name='Paketler')),
                ('elan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Elan', verbose_name='Elan')),
            ],
        ),
    ]
