# Generated by Django 3.0.7 on 2020-10-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_packetelan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packetsarticle',
            name='elan',
        ),
        migrations.AddField(
            model_name='article',
            name='packet',
            field=models.CharField(choices=[('nrml', 'Normal'), ('vip', 'VIP'), ('dmnd', 'DIAMOND'), ('pre', 'PREMIUM')], default='Normal', max_length=50, verbose_name='Paketler'),
        ),
        migrations.AddField(
            model_name='elan',
            name='packet',
            field=models.CharField(choices=[('nrml', 'Normal'), ('vip', 'VIP'), ('dmnd', 'DIAMOND'), ('pre', 'PREMIUM')], default='Normal', max_length=50, verbose_name='Paketler'),
        ),
        migrations.DeleteModel(
            name='PacketElan',
        ),
        migrations.DeleteModel(
            name='PacketsArticle',
        ),
    ]
